name: deploy on push production branch
on:
  push:
    branches:
      - prod

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code to build server
        uses: actions/checkout@v4

      # FIX: Give 'ubuntu' ownership so we can copy files
      - name: set the ubuntu user as owner
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo chown -R ubuntu /var/www/html

      - name: copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./html/*"
          target: "/var/www/html"
          strip_components: 1

      # FIX: Return ownership to root
      - name: restore root ownership
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo chown -R root /var/www/html